services:
  mysql:
    image: mysql:8.4
    container_name: pharmastock-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pharmastockdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: adim
    ports:
      - "3306:3306"
    volumes:
      - pharmastock_mysql_data:/var/lib/mysql

volumes:
  pharmastock_mysql_data:
